### ISSUE TITLE
RuTracker not working

### ISSUE THREAD

**Issue by haldi4803** [demorfi/synox#1]
Hi,
Seems like the Rutracker module doesn't work anymore.
`Haldi@Haldi-W10 /GITHUB/synox
$ php syno.php bt rutracker "Test" "user" "pw"
url:http://rutracker.org/forum/tracker.php?nm=Test
PHP Warning:  Division by zero in /GITHUB/synox/src/bt-rutracker/SynoDLMSearchRutracker.php on line 289
count:0
`

The make command worked fine, and i can enter my password in Synology Downloadmanager and check that. But i never get search results.

**Comment by demorfi** [comment]
Hi. From which country you are trying to access rutracker.org?

**Comment by haldi4803** [comment]
swiss.
If i use the webpage itself it works fine. I can login and search no problem.

**Comment by vt987** [comment]
Hi,
Do you have any news regarding this issue ?

**Comment by vt987** [comment]
Actually it's working for me.. Never mind my previous comment.

LE: I was mistaken.. it's still not working. :(

**Comment by demorfi** [comment]
Version DSM 6?
I can't check the work of rutracker since it is blocked on the territory of Russia.
I'm currently working on an update the synox to be allocated in one module for download station and web interface at api.

**Comment by vt987** [comment]
Yes, DSM v6.. 
I didn't expect rutracker to be blocked in Russia since most of the content is in Russian.

**Comment by maliavko** [comment]
Hi there, I have the same issue and I'm from Belarus. What I've noticed so far:
- I've fixed the script temporary to avoid exception;
- if I login to NAS over SSH and make request manually - I get the response (see response.txt attached);
- if I change URLs to http://rutracker-org.appspot.com/ domain - there is no difference (saw this here http://www.synology-forum.ru/index.php?showtopic=2376&st=240&gopid=67158&#entry67158);

[bt-rutracker.txt](https://github.com/demorfi/synox/files/738421/bt-rutracker.txt)
[respose.txt](https://github.com/demorfi/synox/files/738420/respose.txt)

**Comment by demorfi** [comment]
As the login page, try to use this page http://rutracker-org.appspot.com/forum/login.php?redirect=tracker.php?nm=mors 
since it is redirected to it in 302 Found

**Comment by demorfi** [comment]
It will soon be updated where synox will act as a proxy for search plugins. This will expand and simplify the management of plugins operational update plugins themselves in the future. 
Here is an example of how it will look.
![screen-1](https://cloud.githubusercontent.com/assets/7579267/22623311/db7e6372-eb88-11e6-95e7-cabaca182e42.png)
![screen-2](https://cloud.githubusercontent.com/assets/7579267/22623312/dbb8330e-eb88-11e6-9a10-e0eeec9dd078.png)
For Download Station will be implemented only one plugin synox.

**Comment by maliavko** [comment]
Thanks a lot, haven't had enough time to look into into, seems like I've already tried this URL as in my initial comment above. Anyway, looking forward getting from you that update with unified UI. It would be great to have any update of that event.

**Comment by maliavko** [comment]
Hey dude) I managed to fix it, almost)

The URL you noticed is fine - the only problem I should log out first, there was a captcha so the script failed every time on it, after my "log out" "log in" works as expected. I started getting responses, but still no entries were found. I was going deeper and found that I missed trailing slash at the $pagePrefix constants, fixed it and got valid URLs in the bt-rutracker.log file, but still no entries found. Problem was $entry->getDownload() === 'unknown'. After looking through html-response I noticed that $node items consist unauthorized page. So I had no patience to go deeper and decided to parse entry URL where all necessary information already exists: http://rutracker.org/forum/viewtopic.php?sid=p7Ih3s&t=4244966 - last number is torrent download file ID. After some modification of $item-getDownload() method I got my entries. But! All above works only in SSH through direct request like: php syno.php bt rutracker "embers of a dying world" "my_user_name" "my_pass". I swapped ru-tracker sources with mine, built actual dlm file, installed it on my synology but there is no success: "No matches found" in the GUI.

Pal, I need you help, thank in advance.

**Comment by maliavko** [comment]
I tried to make debug search from synology GUI and got very strange response: google-site-verification. It's clear why I get no entries, but what is the matter can be with this? From ssh all still works fine - 3 entries like from web-face of rutracker.

**Comment by demorfi** [comment]
Synology begin to change due to the plugins algorithm DS. that's why I decided to make all of the plugins in a separate mechanism. The less depending on the hidden code Synology, the longer it will run the plugins and will be easier to restore this.
You can try [Alpha-2](https://github.com/demorfi/synox/tree/alpha-2) it is not stable version, but it is possible you will earn.
Issues or pull requests are welcome.

**Comment by ghost** [comment]
I finally got the repository to build under Windows 10 and Cygwin (with make and zip commands installed). When I add the *.dlm file it says "The search engine plug-in is invalid.". Any suggestions as to what I should try next? I was on the alpha-2 branch btw.

**Comment by demorfi** [comment]
Try to rename the resulting *.dlm file in *.tar.gz and open archiver. dlm is a normal tar in gzip file.
I will check it. Maybe somewhere there is an error.
